### ISSUE TITLE
Is there any plan for documentation?

### ISSUE THREAD

**Issue by mortezarajabi** [FaridAghili/nova-rtl#1]
I was looking for such a package, but unfortunately I couldn't find how to use it.

**Comment by FaridAghili** [comment]
@mortezarajabi

This was my first attempt and I'll archive or delete this repo soon.

Now you can try my other repo which is super easy to use and is under active development.

Give it a try and let me know if anything went wrong:
https://www.github.com/pishran/nova-rtl-theme
